### ISSUE TITLE
Unable to run demo_odometry.py on Jetson TX2(Ubuntu 16.04). python-matplotlib binaries  are installed as sudo apt-get python-matplotlib

### ISSUE THREAD

**Issue by kalkikapoor** [utiasSTARS/pykitti#25]
Error is as shown:
nvidia@tegra-ubuntu:~/kitti/pykitti/demos$ python  demo_odometry.py 
Traceback (most recent call last):
  File "demo_odometry.py", line 5, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/usr/local/lib/python2.7/dist-packages/mpl_toolkits/mplot3d/__init__.py", line 6, in <module>
    from .axes3d import Axes3D
  File "/usr/local/lib/python2.7/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 32, in <module>
    from matplotlib.cbook import _backports
ImportError: cannot import name _backports

Kindly help me resolve this issue.

Thanks

**Comment by kalkikapoor** [comment]
Installing python-mpltoolkits.basemap package resolved this issue.
sudo apt-get install python-mpltoolkits.basemap
